<?php

require_once dirname(__FILE__) . '/../../../../components/Controller.php';

/**
 * Test class for Controller.
 * Generated by PHPUnit on 2012-06-25 at 07:27:21.
 */
class ControllerTest extends CTestCase 
{
    private $_controller;
    private $_layoutName = 'main'; //this value must be equivalent to $layout within /../../../../components/Controller.php
    
    protected function setUp() {
        parent::setUp();
    }

    protected function tearDown() {
    }

    public function testLayoutFileExists() 
    {
        $this->_controller = new Controller('test');
        $this->assertEquals($this->_layoutName, $this->_controller->layout, "Имя используемого по умолчанию шаблона не совпадает с 'main'");
        $this->assertTrue(file_exists(dirname(__FILE__) . '/../../../../views/layouts/' . $this->_layoutName . '.php'), "Файл шаблона, используемого по умолчанию, не обнаружен");
    }
}