<?php

require_once dirname(__FILE__) . '/../../../../components/Helpers.php';

/**
 * Test class for Helpers.
 * Generated by PHPUnit on 2012-06-18 at 09:56:52.
 */
class HelpersTest extends CTestCase 
{
    protected function setUp(){
        parent::setUp();
    }

    protected function tearDown(){
    }

    public function testCreateUrl()
    {
        $resource_name = "/test";
        $expected = "/index-test.php/test";
        $this->assertSame($expected, Helpers::createUrl($resource_name));
    }

    public function testCreateHash()
    {
        $expected = "cf798d919ced9e86f70814173745990e97b09bbd"; // reference hash of $username and $password that you see below
        $username = "asv909";
        $password = "ErTrd-2007";
        $salt = "4fc5c61db89199.64581532"; // reference salt of $username and $password that you see above
        $suffix = "249?6H3xyz!"; // this value must be equivalent to $suffix within /../../../../../../modules/service/ServiceModule.php
        $this->assertSame($expected, Helpers::createHash($username, $password, $salt, $suffix));
    }

    public function testRestrictNumberOfAttempts()
    {
        $restricts = array(
            'numberOfAttempts' => 2,
            'timeout' => 5
        );
        $this->assertFalse(Helpers::restrictNumberOfAttempts($restricts));
        $this->assertTrue(Helpers::restrictNumberOfAttempts($restricts));
        sleep($restricts['timeout']+1);
        $this->assertFalse(Helpers::restrictNumberOfAttempts($restricts));
    }
}
?>