<?php

require_once dirname(__FILE__) . '/../../../../components/Helpers.php';

/**
 * Test class for Helpers.
 * Generated by PHPUnit on 2012-06-18 at 09:56:52.
 */
class HelpersTest extends CTestCase 
{
    protected function setUp()
    {
        parent::setUp();
    }

    protected function tearDown()
    {}

    /**
     * @group manager
     */    
    public function testCreateUrl()
    {
        $resourceName_ = '/test';
        $expected_ = '/index-test.php/test';
        $this->assertSame($expected_, Helpers::createUrl($resourceName_));
    }

    /**
     * @group manager
     */    
    public function testCreateHash()
    {
        // reference hash of $username and $password that you see below
        $expected_ = 'cf798d919ced9e86f70814173745990e97b09bbd';
        $username_ = 'asv909';
        $password_ = 'ErTrd-2007';
        // reference salt of $username and $password that you see above
        $salt_ = '4fc5c61db89199.64581532';
        // this value must be equivalent to $suffix within /../../../../../../modules/service/ServiceModule.php
        $suffix_ = '249?6H3xyz!'; 
        $this->assertSame($expected_,
                          Helpers::createHash($username_, $password_, $salt_, $suffix_));
    }

    /**
     * @group manager
     */    
    public function testRestrictNumberOfAttempts()
    {
        $restricts_ = array('numberOfAttempts' => 2, 'timeout' => 5);
        $this->assertFalse(Helpers::restrictNumberOfAttempts($restricts_));
        $this->assertTrue(Helpers::restrictNumberOfAttempts($restricts_));
        sleep($restricts_['timeout']+1);
        $this->assertFalse(Helpers::restrictNumberOfAttempts($restricts_));
    }
}