<?php

require_once dirname(__FILE__) . '/../../../WebTestCase.php';

/**
 * Test class for WebTestCase.
 * Generated by PHPUnit on 2012-06-20 at 14:37:07.
 */
class WebTestCaseTest extends CTestCase 
{
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() 
    {
        parent::setUp();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {}

    public function testForTesting() 
    {
        $this->object = new WebTestCase;
        $this->assertTrue($this->object->forTesting());
    }

}

?>
