<?php

require_once dirname(__FILE__) . '/../../../WebTestCase.php';

/**
 * Test class for WebTestCase.
 * Generated by PHPUnit on 2012-06-20 at 14:37:07.
 */
class WebTestCaseTest extends CTestCase 
{
    protected $object;

    protected function setUp() {
        parent::setUp();
    }

    protected function tearDown() {
    }

    /**
     * @group common
     */    
    public function testForTesting() 
    {
        $this->object = new WebTestCase;
        $this->assertTrue($this->object->forTesting());
    }

}