<?php

require_once dirname(__FILE__) . '/../../../../../../modules/service/models/Manager.php';
require_once dirname(__FILE__) . '/../../../../../../modules/service/components/ManagerIdentity.php';
require_once dirname(__FILE__) . '/../../../../../../components/Helpers.php';

/**
 * Test class for Manager.
 * Generated by PHPUnit on 2012-06-13 at 12:53:56.
 */
class ManagerTest extends CDbTestCase {

    /**
     * @var manager
     */
    private $manager;
    private $valid_data = array(
        'username' => 'asv909',
        'password' => 'ErTrd-2007',
        'rememberMe' => FALSE,
        'verifyCode' => 'dolotut'
        );
    
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() 
    {
        parent::setUp();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {}

    public function testTableNameIsExist() 
    {
        $this->manager = new Manager;
        $this->assertEquals($this->manager->tableName(),$this->manager->tableSchema->name);
    }

    public function testAuthenticate() 
    {
        // for valid data
        $this->manager = new Manager;
        $this->manager->attributes = $this->valid_data;
        $this->assertTrue($this->manager->authenticate());
        // for unknown username
        $username = $this->manager->username;
        $this->manager->username = "unknown";
        $this->assertFalse($this->manager->authenticate());
        $this->manager->username = $username;
        // for wrong password having length > 12 char so that 1st condition if(!$this->hasErrors()) would FALSE
        $password = $this->manager->password;
        $this->manager->password = "wrong_password";
        $this->assertFalse($this->manager->authenticate());
        $this->manager->password = $password;
        // for wrong password < 12 char
        $this->valid_data['password'] = "wrong_pass";
        $this->manager = new Manager;
        $this->manager->attributes = $this->valid_data;
        $this->assertFalse($this->manager->authenticate());
    }

    public function testLogin() 
    {
        //оnly for case $rememberMe=FALSE
        $this->manager = new Manager;
        $this->manager->attributes = $this->valid_data;
        $this->manager->authenticate();
        $this->assertTrue($this->manager->login());
        //to 1st condition if($this->_identity===null) would TRUE
        $this->manager = new Manager;
        $this->manager->attributes = $this->valid_data;
        $this->assertFalse($this->manager->login());
    }
    
    public function testAttributeLabels() 
    {
        $this->manager = new Manager;
        $this->assertType('array', $this->manager->attributeLabels());
        $this->assertNotEmpty($this->manager->attributeLabels());
        $attr_labels = $this->manager->attributeLabels();
        $this->assertEquals('Логин', $attr_labels['username']);
        $this->assertEquals('Пароль', $attr_labels['password']);
    }
    
    public function testRules() 
    {
        $this->manager = new Manager;
        $this->assertType('array', $this->manager->rules());
        $this->assertNotEmpty($this->manager->rules());        
    }
    
    public function testModel()
    {
        $this->manager = new Manager;
        $this->assertNotEmpty($this->manager->model());
    }
}
?>