<?php

require_once dirname(__FILE__) . '/../../../../../../modules/service/models/Url.php';

/**
 * Test class for Url.
 * Generated by PHPUnit on 2012-08-30 at 14:24:21.
 */
class UrlTest extends CDbTestCase 
{
    private $_url;

    protected function setUp()
    {
        parent::setUp();
    }

    protected function tearDown()
    {}
    
    public function testTableNameIsExist()
    {
        $this->_url = new Url;
        $this->assertEquals($this->_url->tableName(), $this->_url->tableSchema->name);
    }
    
    public function testModel()
    {
        $this->_url = new Url;
        $this->assertNotEmpty($this->_url->model());
    }

}

?>
