<?php

require_once dirname(__FILE__) . '/../../../../../../modules/service/controllers/ManagerController.php';

/**
 * Test class for ManagerController.
 * Generated by PHPUnit on 2012-06-20 at 14:29:37.
 */
class ManagerControllerTest extends CTestCase 
{
    /**
     * @var ManagerController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() 
    {
        parent::setUp();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {}

    /**
     * @todo Implement testFilters().
     */
    public function testFilters() 
    {}

    /**
     * @todo Implement testAccessRules().
     */
    public function testAccessRules() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testActions().
     */
    public function testActions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testActionIndex().
     */
    public function testActionIndex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testActionLogin().
     */
    public function testActionLogin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testActionLogout().
     */
    public function testActionLogout() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
